# The log file location
log:
  filename: "DAS.log"

# All the databases used by the system
databases:
  dev: "data/DAS.sqlite"
  stage: ""
  prod: ""
  engine: "peewee.SqliteDatabase"
# For every config option for flask
# For every table in the database, add an item here
models:
  mainDB:
  - Role
  - User
  - UserRole
  - Notification
  - Request
  - Status
  - File
  
flask:
  secret_key: '123456790'
  debug: True
flask_security:
  security_password_hash: "pbkdf2_sha512"
  security_password_salt: "ATGUOHAELKiubahiughaerGOJAEGj"
  
# this makes the navigation bar     #src: "/static/images/NavLogo.png"
LaborNavibar:
  - title: "DAS Database"
    link: "/index"
  - title: "Upload"
    link: "/upload"
    
StudentNavibar:
  - title: "DAS Database"
    link: "/index"
  - title: "Request Alt. Text"
    link: "/request"

fileOperations:
  allowedExtension:
    pdf: "pdf"
    doc: "doc"
    docx: "docx"
  allowedSize:
    size: 8000000
  dataPaths:
    uploads: "static/files/uploads"
    zips: "static/files/zips"
    temp: "static/files/tmp"